
extends:
  - "airbnb"
  - "airbnb-typescript"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "plugin:react/recommended"
  - "next/core-web-vitals"
  - "next"
  - "plugin:react-hooks/recommended"
  - "plugin:react/recommended"
  - "plugin:react-prefer-function-component/recommended"

env:
  browser: true
  es6: true
  jest: true

parser:
  "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2018
  project: true
  tsconfigRootDir: "../tsconfig.json"


plugins:
  - "@typescript-eslint"
  - "react"
  - "react-hooks"
  - "react-prefer-function-component"

root: false

rules:
  "import/extensions": [
    "error",
    "ignorePackages",
    {
      "": "never",
      "ts": "never",
      "tsx": "never"
    }
  ]
  "react/react-in-jsx-scope": "off"
  "@typescript-eslint/no-unused-vars": "error"
  "@typescript-eslint/no-use-before-define": "off"
  "import/prefer-default-export": "off"
  "react/function-component-definition": [2, { "namedComponents": "arrow-function" }]
  "import/no-cycle": "off"
  "react/jsx-no-useless-fragment": "off"
